var stateData = {
	usa: {
		class: 'N/A',
		mainw: 'N/A',
		awakew: 'N/A',
		attackt: 'N/A',
		strengths: 'N/A ',
		weaknesses: 'N/A',
	},
	war: {
		class: 'Warrior',
		mainw: 'Sword and Shield',
		awakew: 'Greatsword',
		attackt: 'Melee',
		strengths: 'Has a good block, very strong small scale combat (i.e. 10v10 or 20v20), very mobile class, very strong at 1v1, versatile combos ',
		weaknesses: 'Not strong in large scale, vulnerable to crowd control skills (i.e. stuns, stiffs, knockdowns), need a lot of gear and high skill cap to play large scale',

	},
	valk: {
		class: 'Valkyrie',
		mainw: 'Sword and Shield',
		awakew: 'Lancia',
		attackt: 'Melee',
		strengths: 'Most powerful block in game, large array of crowd control skills, high damage scaling ',
		weaknesses: 'immobile class, very large stamina consumption, unprotected movement options, long cooldowns, cannot catch strong movement classes easily',
	},
	zerk: {
		class: 'Bersker',
		mainw: 'Doubles Axes and knot',
		awakew: 'Buster Cannon',
		attackt: 'Melee with ranged harrass',
		strengths: 'Multiple grabs, has a ranged harrass, has a very high scaling damage skill, cult following, My friend Obsidian plays this ',
		weaknesses: 'Limited viable skills, long cooldowns, unsafe movement options, easily stopped when trying to engage ',
	},
	sorc: {
		class: 'Sorceress',
		mainw: 'Amulet and Talisman',
		awakew: 'Scythe',
		attackt: 'Melee',
		strengths: 'Extremely mobile class, has a lot of iframes that allow it to avoid enemy damage and crowd control,  can make itself a mist to go untargetable for a few seconds ',
		weaknesses: 'If you do not have a high stamina level movement will be an issue, does not do good in large forces it is better to pick targets off on the side',
	},
	rang: {
		class: 'Ranger',
		mainw: 'Bow and dagger',
		awakew: 'Kamasylvia Sword',
		attackt: 'Melee/Range',
		strengths: 'Very strong ranged damage, good mobility and skill so they can exit and engage if they feel they cannot win ',
		weaknesses: 'When escape moves are on cooldown highly sceceptible to crowd control and cannot escape when being enganged on',
	},
	wiz: {
		class: 'Wizard',
		mainw: 'Staff and dagger',
		awakew: 'God Sphera',
		attackt: 'Range',
		strengths: 'A lot of super armors, can dive into an enemy ball with the only fear of getting grabbeed, not easily knocked down, has a grab ',
		weaknesses: 'All the skills have very long animations so can easily be grabbed, not a lot of movement when teleport skill is on cooldown',
	},
	witch: {
		class: 'Witch',
		mainw: 'Staff and dagger',
		awakew: 'Aad Sphera',
		attackt: 'Range',
		strengths: 'More super armors than wizard and higher damage scaling than its male counterpart wizard ',
		weaknesses: 'Same weaknesses as wizard very long skill animations and not a lot of movement options but does not have a grab like wizards do',
	},
	nin: {
		class: 'Ninja',
		mainw: 'Shortsword and Shuriken',
		awakew: 'Sura Katana',
		attackt: 'Melee',
		strengths: 'High scale on damage can go invisible for a long time to avoid confrontation, and come out of invisibility when the time is right ',
		weaknesses: 'Ninja is currently a very strong class and only has a few weaknesses and you need good timing to beat it 1v1, has weak natural defenses',
	},
	kuno: {
		class: 'Kunoichi',
		mainw: 'Shortsword and Kunai',
		awakew: 'Chakram',
		attackt: 'Melee',
		strengths: 'Just like ninja they stay invisble for an extended amount of time, and can strike at will.  A lot of area of effect crowd control skills stuns a lot of people with one move. ',
		weaknesses: 'Currently the same as ninja their only real weakness is weak natural defense',
	},
	musa: {
		class: 'Musa',
		mainw: 'Blade and Hornbow',
		awakew: 'Crescent Blade',
		attackt: 'Melee',
		strengths: 'Extremely fast, Protected movement, after certain attack power they shred through enemies easily, large area of effect skills ',
		weaknesses: 'Very large stamina consumption, once they stop moving they are easily defeated',
	},
	mae: {
		class: 'Maewha',
		mainw: 'Blade and Hornbow',
		awakew: 'Kerispear',
		attackt: 'Melee',
		strengths: 'Extremely fast, Protected movement, great single target damage per second, easily pick off targets that are on the side or by themselves ',
		weaknesses: 'same as male counterpart Musa, very large stamina consumption, once they stop moving they are easily defeated, their skills are very single target cannot hit large groups of people',
	},

};
